#!/usr/bin/perl
# $Id: wordfreq.perl,v 1.13 2001/05/16 23:46:40 doug Exp $
# http://dada.perl.it/shootout/wordfreq.perl.html
# Tony Bowden suggested using tr versus lc and split(/[^a-z]/)

use strict;

open INF, "<" . $ARGV[0];
open OUTF, ">" . $ARGV[1];

my %count = ();
while (read(INF, $_, 4095) and $_ .= <INF>) {
    tr/A-Za-z/ /cs;
    ++$count{$_} foreach split(' ', lc $_);
}

my @lines = ();
my ($w, $c);
push(@lines, sprintf("%7d\t%s\n", $c, $w)) while (($w, $c) = each(%count));
print OUTF sort { $b cmp $a } @lines;

close(INF);
close(OUTF);

